### ISSUE TITLE
Minecraft is no longer signing me in

### ISSUE THREAD

**Issue by SpectralArc** [mindstorm38/portablemc#121]
When starting I go into singleplayer, my skin is missing and trying to join a server gives me the message "Failed to log in: Invalid session (try restarting your game and the launcher)". I can confirm this is not an issue with mods as I tried portablemc on vanilla and the same issue persisted. I am pretty confused, please help!
I attached my logs as well if that can help.
[latest.log](https://github.com/mindstorm38/portablemc/files/10017362/latest.log)

**Comment by mindstorm38** [comment]
What's your command line?

**Comment by LimeDev8756** [comment]
Same issue here! I can share my command line if you want

**Comment by LimeDev8756** [comment]
"py portablemc.exe --work-dir "not/a/real/directory" start fabric:1.19.2:0.14.10"

dont mind the portablemc.exe and not portablemc lol, that might be another bug, i have to put portable.exe or python will be confused

**Comment by LimeDev8756** [comment]
hint : put -m -l {email} on the end, LOL

**Comment by mindstorm38** [comment]
Ah! Sure it doesn't work without it ahah. For the .exe issue, I think it's related to pip or your path, and not portablemc: pip builds de .exe, and it's just a wrapper for launcher of a python module.

**Comment by loneneuron** [comment]
Getting a different error here, running `portablemc login -m email@example.com` returns:
```
[  ..  ] Authenticating email@example.com with Microsoft...
[      ] Processing authentication against Minecraft services...Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Mustafa\AppData\Local\Programs\Python\Python311\Scripts\portablemc.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mustafa\AppData\Local\Programs\Python\Python311\Lib\site-packages\portablemc\cli.py", line 145, in main
    cmd(handler, ns)
  File "C:\Users\Mustafa\AppData\Local\Programs\Python\Python311\Lib\site-packages\portablemc\cli.py", line 350, in cmd
    handler(ns, new_context(ns))
  File "C:\Users\Mustafa\AppData\Local\Programs\Python\Python311\Lib\site-packages\portablemc\cli.py", line 577, in cmd_login
    sess = prompt_authenticate(ctx, ns.email_or_username, True, ns.microsoft)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mustafa\AppData\Local\Programs\Python\Python311\Lib\site-packages\portablemc\cli.py", line 953, in prompt_authenticate
    session = prompt_microsoft_authenticate(auth_db.get_client_id(), email)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mustafa\AppData\Local\Programs\Python\Python311\Lib\site-packages\portablemc\cli.py", line 1067, in prompt_microsoft_authenticate
    return MicrosoftAuthSession.authenticate(client_id, app_id, server.ms_auth_code, code_redirect_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mustafa\AppData\Local\Programs\Python\Python311\Lib\site-packages\portablemc\__init__.py", line 1108, in authenticate
    res = cls.authenticate_base({
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mustafa\AppData\Local\Programs\Python\Python311\Lib\site-packages\portablemc\__init__.py", line 1160, in authenticate_base
    xsts_token = res["Token"]
                 ~~~^^^^^^^^^
KeyError: 'Token'
```

**Comment by mindstorm38** [comment]
Weird, it works for me... Could you add a debug print at this particular line? I would like to know what contains the `res` (ofc please remove any sensitive information). I'm not an expert in Microsoft authentication, so I may have missed a detail in the API.

**Comment by mindstorm38** [comment]
Ok I acknowledge the edit!

**Comment by mindstorm38** [comment]
By the way I'll try soon to default login to Microsoft instead of Yggdrasil, the latter being deprecated, and I guess rarely used, I don't see why it should stay the default option.

**Comment by loneneuron** [comment]
Good idea. 👍

**Comment by mindstorm38** [comment]
Any update? Note that latest version has support for `certifi` (if installed) in order to fix certificate problems when logging in for example.

**Comment by mindstorm38** [comment]
Btw, with the latest release 4.0.0, the authentication defaults to Microsoft. I close this issue as it is abandoned by original poster, please re-open if problem persists.
