### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by BlueBerrySans365** [mindstorm38/portablemc#132]
Hello! I want to install forge version via API, but i still don't know how exactly to do it. Maybe i need to add something in Version(ctx, version_id)?

**Comment by mindstorm38** [comment]
You can use the [portablemc-fabric](https://github.com/mindstorm38/portablemc/blob/master/src/forge/README.md) add-on, it provides a `ForgeVersionInstaller` class that provide methods for installing (if needed) a forge version, once this is done you can access the `version` attribute that works lke a regular `Version` class!

**Comment by BlueBerrySans365** [comment]
Oh, thanks, i tried right now. There is new error :
```
Traceback (most recent call last):
  File "/home/nicksalt/MCLAUNCH/app.py", line 13, in <module>
    dl_report = version.install()
  File "/home/nicksalt/.local/lib/python3.10/site-packages/portablemc_forge/__init__.py", line 230, in install
    raise ValueError()
ValueError
```

**Comment by mindstorm38** [comment]
You're missing a call to `version.prepare` before `version.install`, you should also only call these functions if `installer.needed()` returns true.

**Comment by BlueBerrySans365** [comment]
Sorry, i was busy lately.
So, i added ``version.prepare()`` how you said. Now it gives me another error ._.
```
Traceback (most recent call last):
  File "E:\LSMPR\mc\asa.py", line 15, in <module>
    dl_report = version.install()
  File "C:\Users\NickSalt\AppData\Local\Programs\Python\Python310\lib\site-packages\portablemc_forge\__init__.py", line 233, in install
    wrapper_completed = subprocess.run([
  File "C:\Users\NickSalt\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\NickSalt\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\NickSalt\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by mindstorm38** [comment]
Hi, the latest launcher's version has just been released, it provides a better API. Could you try it? The documentation has been updated so you have examples for installing forge!
