### ISSUE TITLE
portablemc Fails to Authenticate user

### ISSUE THREAD

**Issue by slenered** [mindstorm38/portablemc#134]
the command's output is
```
>portablemc login -m @gmail.com
[  ..  ] Authenticating @gmail.com with Microsoft...
[      ] Processing authentication against Minecraft services...
[FAILED] This operation requires an operational network, but a socket error happened: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
```

**Comment by snoopchallenge** [comment]
having same issue

**Comment by mindstorm38** [comment]
Same here, I'm investigating...

**Comment by mindstorm38** [comment]
I wonder if this could be Mojang's fault... One of their APIs must provide an expired certificate

**Comment by mindstorm38** [comment]
Anyone having the same issue at the moment? I'm no longer able to reproduce...

**Comment by slenered** [comment]
I am
`[FAILED] This operation requires an operational network, but a socket error happened: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>`

**Comment by slenered** [comment]
I was able to bypass the problem by modifying the program

open the install location `(default location): C:\Users\(user)\AppData\Roaming\Python\Python310\site-packages\portablemc`
open the `__init__.py` file,
add to line 40:
```
import ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
```
then on line 1693 replace `res: HTTPResponse = url_request.urlopen(req, timeout=timeout)` to `res: HTTPResponse = url_request.urlopen(req, timeout=timeout, context=ctx)`

this skips verifying site certificates.

**Comment by mindstorm38** [comment]
Do you know precisely which url cause this error? @slenered

**Comment by slenered** [comment]
never-mind I still get the error I just had a validate session when I tested it
`[  OK  ] Session validated for @gmail.com.`

**Comment by mindstorm38** [comment]
Working on it...

**Comment by mindstorm38** [comment]
Ok I found why not everybody has the issue. It seems that not everybody has the latest Root Certificates on their system, because python's urllib is using system available certificates. So I'm working on a fallback to using the `certifi` lib (used by requests) when available, and suggesting the user to install it when encountering the issue.

**Comment by mindstorm38** [comment]
Coming soon... https://github.com/mindstorm38/portablemc/commit/3ab02af71dfba426d132d64631c562fe65c91b6c

**Comment by slenered** [comment]
I have certifi, but it didn't help

**Comment by mindstorm38** [comment]
Yes it requires some changes in the source code for using it in the context.

**Comment by dakiba** [comment]
I have maybe a similar problem:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "urllib\request.py", line 1317, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "http\client.py", line 1422, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\portablemc\http.py", line 95, in http_request
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\portablemc\auth.py", line 281, in authenticate_base
  File "site-packages\portablemc\auth.py", line 344, in ms_request
  File "site-packages\portablemc\http.py", line 100, in http_request
portablemc.http.HttpError: (<HttpResponse 0>, 'POST', 'https://login.live.com/oauth20_token.srf', URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
  File "main.py", line 135, in start_minecraft
  File "minecraft.py", line 123, in start
  File "auth.py", line 95, in prompt_microsoft_authenticate
  File "site-packages\portablemc\auth.py", line 263, in authenticate
  File "site-packages\portablemc\auth.py", line 283, in authenticate_base
portablemc.auth.OutdatedTokenError
```

**Comment by mindstorm38** [comment]
Have you "certifi" installed?

**Comment by dakiba** [comment]
No, this are my packages:
```
Package                   Version
------------------------- -------
altgraph                  0.17.4
customtkinter             5.2.1
darkdetect                0.8.0
gitdb                     4.0.11
GitPython                 3.1.40
packaging                 23.2
Pillow                    10.1.0
pip                       23.3.1
portablemc                4.1.0
psutil                    5.9.6
pyinstaller               6.2.0
pyinstaller-hooks-contrib 2023.10
setuptools                59.6.0
smmap                     5.0.1
```

And the errors comes on a specific windows 10 system. My launcher that I build, work on most PCs but on that specific one, comes that error.

**Comment by mindstorm38** [comment]
Try including certifi, we already had the issue in the past. This package provide up to date root certificate in case your system is out of date, and the launcher supports it when installed.

**Comment by dakiba** [comment]
this seems to work. thx
