### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '~/Library/Application Support/minecraft/jvm/java-runtime-gamma/bin/java'

### ISSUE THREAD

**Issue by plushTeddy** [mindstorm38/portablemc#149]
Hello, i tried to install it on my mac but I got this error!

```[FAILED] An unexpected error happened, please report it to the authors:
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/portablemc/cli.py", line 350, in cmd
    handler(ns, new_context(ns))
  File "~/.local/lib/python3.10/site-packages/portablemc/cli.py", line 566, in cmd_start
    start.start()
  File "~/.local/lib/python3.10/site-packages/portablemc/__init__.py", line 843, in start
    self.runner([
  File "~/.local/lib/python3.10/site-packages/portablemc/__init__.py", line 858, in default_runner
    subprocess.run(args, cwd=cwd)
  File "~/anaconda3/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "~/anaconda3/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "~/anaconda3/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '~/Library/Application Support/minecraft/jvm/java-runtime-gamma/bin/java'
```

I would be very happy if you could help me!

**Comment by mindstorm38** [comment]
Should be fixed in the upcoming v4 update... Re-open if reproduced.
