### ISSUE TITLE
not able to login when launching

### ISSUE THREAD

**Issue by viper968** [mindstorm38/portablemc#150]
OS: Void Linux
Browser that i am using for microsoft sign in: Brave, appimage
Error that portableMC gave me:
[name@VENOM ~]$ python3 -m portablemc --work-dir /home/name/Games/Minecraft/1.19.4_fabric/work --main-dir /home/name/Games/Minecraft/1.19.4_fabric/main start fabric:1.19.4 -m -l email_placeholder
[  OK  ] Resolving fabric loader for 1.19.4...
[  OK  ] Resolved version fabric-1.19.4-0.14.21.
[  OK  ] Loaded version JAR.    
[  OK  ] Checked 3570 assets.
[  OK  ] Loaded pretty logger.
[  OK  ] Loaded 64 libraries. 
[  OK  ] Loaded Mojang Java 17.0.3.
[  ..  ] Authenticating email_placeholder with Microsoft...
[      ] Opened authentication page in browser.../tmp/.mount_Brave-UKirBk
Opening in existing browser session.
[      ] Processing authentication against Minecraft services...
[FAILED] An unexpected error happened, please report it to the authors:
Traceback (most recent call last):
  File "/home/name/.local/lib/python3.11/site-packages/portablemc/cli.py", line 350, in cmd
    handler(ns, new_context(ns))
  File "/home/name/.local/lib/python3.11/site-packages/portablemc/cli.py", line 808, in wrapper
    return func(orig_func, *w_args, **w_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/portablemc_forge/__init__.py", line 30, in cmd_start
    return old(ns, ctx)
           ^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/portablemc/cli.py", line 808, in wrapper
    return func(orig_func, *w_args, **w_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/portablemc_fabric/__init__.py", line 29, in cmd_start
    return old(ns, ctx)
           ^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/portablemc/cli.py", line 546, in cmd_start
    start_opts.auth_session = prompt_authenticate(ctx, ns.login, not ns.temp_login, ns.microsoft, ns.anonymise)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/portablemc/cli.py", line 961, in prompt_authenticate
    session = prompt_microsoft_authenticate(auth_db.get_client_id(), email)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/portablemc/cli.py", line 1075, in prompt_microsoft_authenticate
    return MicrosoftAuthSession.authenticate(client_id, app_id, server.ms_auth_code, code_redirect_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/portablemc/__init__.py", line 1137, in authenticate
    res = cls.authenticate_base({
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/portablemc/__init__.py", line 1189, in authenticate_base
    xsts_token = res["Token"]
                 ~~~^^^^^^^^^
KeyError: 'Token'

I have no clue what this means but it said report it to the authors, and that is what i am doing.

**Comment by viper968** [comment]
well...it works now for no reason that i can see what so ever...
