### ISSUE TITLE
DoesNotOwnMinecraftError within auth_session.refresh()

### ISSUE THREAD

**Issue by dakiba** [mindstorm38/portablemc#193]
Some user get now the DoesNotOwnMinecraftError Exception, then they want refresh the session:

```python
        from portablemc.fabric import FabricVersion
        from portablemc.standard import Context

        if data.get("auth_mails").get(email, {}).get("auth"):
            auth_session = data.get("auth_mails").get(email, {}).get("auth")
            if not auth_session.validate():
                auth_session.refresh()
```

```
Traceback (most recent call last):
  File "minecraft.py", line 121, in start
  File "site-packages\portablemc\auth.py", line 226, in refresh
  File "site-packages\portablemc\auth.py", line 326, in authenticate_base
portablemc.auth.DoesNotOwnMinecraftError
```

Line 121 is the auth_session.refresh()

**Comment by dakiba** [comment]
Reset the session didn't worked. After we login to the mojang website in the browser, the error was gone. We had now 2 users with that issue. Microsoft is so ......

**Comment by mindstorm38** [comment]
I'm afraid of Microsoft API honestly
