### ISSUE TITLE
[FAILED] metadata: /javaVersion/majorVersion must be an integer

### ISSUE THREAD

**Issue by draklowell** [mindstorm38/portablemc#229]
Error when trying to download neoforge for 1.20.4:

```
$> portablemc -vvv start neoforge:1.20.4
[ INFO ] Global version: neoforge 1.20.4 
[  OK  ] Resolved neoforge 20.4.237        
[  OK  ] Loaded version neoforge-20.4.237     
[  OK  ] Loaded version 1.20.4     
[ INFO ] Features: []
[FAILED] metadata: /javaVersion/majorVersion must be an integer
Traceback (most recent call last):
  File "/home/draklowell/.local/lib/python3.10/site-packages/portablemc/cli/__init__.py", line 148, in cmd
    handler(ns)
  File "/home/draklowell/.local/lib/python3.10/site-packages/portablemc/cli/__init__.py", line 379, in cmd_start
    env = version.install(watcher=StartWatcher(ns))
  File "/home/draklowell/.local/lib/python3.10/site-packages/portablemc/standard.py", line 321, in install
    self._resolve_jvm(watcher)  # JVM added here on purpose to ease implementation of ForgeVersion
  File "/home/draklowell/.local/lib/python3.10/site-packages/portablemc/standard.py", line 871, in _resolve_jvm
    raise ValueError("metadata: /javaVersion/majorVersion must be an integer")
ValueError: metadata: /javaVersion/majorVersion must be an integer
```

**Comment by draklowell** [comment]
JVM issue, sorry
