### ISSUE TITLE
Trying to launch forge will result in a 403 forbidden error

### ISSUE THREAD

**Issue by creator1116** [mindstorm38/portablemc#235]
`[ INFO ] Global version: forge 1.8.9
[FAILED] Unhandled HTTP error happened:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\portablemc\http.py", line 95, in http_request
    res: HTTPResponse = urllib.request.urlopen(req, context=ctx)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\portablemc\cli\__init__.py", line 148, in cmd
    handler(ns)
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\portablemc\cli\__init__.py", line 379, in cmd_start
    env = version.install(watcher=StartWatcher(ns))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\portablemc\standard.py", line 318, in install
    self._resolve_version(watcher)
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\portablemc\forge.py", line 68, in _resolve_version
    promo_versions = request_promo_versions()
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\portablemc\forge.py", line 488, in request_promo_versions
    return http_request("GET", "https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json",
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\portablemc\http.py", line 98, in http_request
    raise HttpError(HttpResponse(cast(HTTPResponse, error)), method, url, error)
portablemc.http.HttpError: (<HttpResponse 403>, 'GET', 'https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json', <HTTPError 403: 'Forbidden'>)

this error is what  shows up whenever i try to launch mc could it be my version? (1.8.9)

**Comment by Ristovski** [comment]
Seems like `https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json` (and possibly other endpoints) now sits behind Cloudflare which might decide to present a captcha...

**Comment by creator1116** [comment]
whats the fix?

**Comment by creator1116** [comment]
will using cloudflare dns help?

**Comment by mindstorm38** [comment]
> will using cloudflare dns help?

I don't think

**Comment by mindstorm38** [comment]
It works on my side (just tried `pmc start forge:1.8.9`), you could try to specific the full exact game version and loader version: `pmc start forge:forge:1.8.9-11.15.1.2318`.

**Comment by creator1116** [comment]
looks like its fine now. for some reason

**Comment by creator1116** [comment]
thanks
