### ISSUE TITLE
Incompatible with 1.21.2/3

### ISSUE THREAD

**Issue by CommandGenius** [mindstorm38/portablemc#237]

**Comment by mindstorm38** [comment]
Could you elaborate? It works on my setup and these versions have been up for a month at least, so I wonder why nobody reported this before.

**Comment by CommandGenius** [comment]
> Could you elaborate? It works on my setup and these versions have been up for a month at least, so I wonder why nobody reported this before.

I get an error that says "Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/C:/Users/user/AppData/Roaming/.minecraft/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar!/org/objectweb/asm/ClassReader.class, jar:file:/C:/Users/user/AppData/Roaming/.minecraft/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar!/org/objectweb/asm/ClassReader.class
        at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:83)
        at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)"

**Comment by mindstorm38** [comment]
Yes it has been fixed just a few versions back, thanks for using PMC!
