### ISSUE TITLE
No such file or directory with login subcommand

### ISSUE THREAD

**Issue by mindstorm38** [mindstorm38/portablemc#39]
**Describe the bug**
When using `login` sub command with and non-existing working directory.

**To Reproduce**
PortableMC version: `2.0.3`
Python version: `3.8.10`
Add-ons: none
- Ensure that the working directory does not exists.
- Use `portablemc login [-m] <email>`
```
Traceback (most recent call last):
  File "~/.local/bin/portablemc", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.8/site-packages/portablemc/cli.py", line 126, in main
    handler(ns, new_context(ns))
  File "~/.local/lib/python3.8/site-packages/portablemc/cli.py", line 508, in cmd_login
    sess = prompt_authenticate(ctx, ns.email_or_username, True, ns.microsoft)
  File "~/.local/lib/python3.8/site-packages/portablemc/cli.py", line 775, in prompt_authenticate
    auth_db.save()
  File "~/.local/lib/python3.8/site-packages/portablemc/__init__.py", line 985, in save
    with open(self.filename, "wt") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '~/.minecraft/portablemc_auth.json
```

**Expected behavior**
The authentication session must be saved to the `<working_dir>/portablemc_auth.json`.

**Screenshots**
None

**Additional context**
None

**Comment by mindstorm38** [comment]
Fix available on the next release 2.0.4
