### ISSUE TITLE
Raspberry Pi 4B LWJGL error

### ISSUE THREAD

**Issue by ManBearPig0** [mindstorm38/portablemc#68]
**Describe the bug**
I logged in with a microsoft account, installed openjdk 17 but failed to launch minecraft 1.8.9.
```
$ uname -a
Linux rpi 5.15.21-2-rpi-ARCH #1 SMP PREEMPT Thu Feb 10 05:54:08 MST 2022 aarch64 GNU/Linux
$ portablemc start 1.8.9 --lwjgl 3.2.3 --jvm java
[  OK  ] Resolved version 1.8.9.    
[  OK  ] Fixed LWJGL version to 3.2.3
[  OK  ] Loaded version JAR.    
[  OK  ] Checked 734 assets.
[  OK  ] Loaded pretty logger.
[  OK  ] Loaded 47 libraries. 
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int org.lwjgl.DefaultSysImplementation.getPointerSize()'
	at org.lwjgl.DefaultSysImplementation.getPointerSize(Native Method)
	at org.lwjgl.Sys.<clinit>(Sys.java:118)
	at ave.J(SourceFile:2539)
	at net.minecraft.client.main.Main.main(SourceFile:41)
```

**To Reproduce**
PortableMC version: 2.3.0
Python version: 3.10.2-1

**Expected behavior**
Launch minecraft 1.8.9.

**Additional context**
Line with username removed. lwjgl 3.3.0 has this same output. I tried java-11-openjdk and java-17-openjdk using `archlinux-java`, both have this same output. There is no log file in ~/.minecraft/ directly. Where should one be?

**Comment by ManBearPig0** [comment]
I see, minecraft started using lwjgl 3 as of release 1.13.
