### ISSUE TITLE
Forge not installing

### ISSUE THREAD

**Issue by MTM828** [mindstorm38/portablemc#87]
**Describe the bug**
While running `portablemc start forge:`, I get this output:
```
[  OK  ] Resolved forge 1.19-41.0.100, downloading installer and parent version.
[  OK  ] Downloaded 1/2 files, 6.7MB in 61.6s (1 errors).                       
         https://maven.minecraftforge.net/net/minecraftforge/forge/1.19-41.0.100-1.19/forge-1.19-41.0.100-1.19-installer.jar: Not found
[      ] Running installer (can take few minutes)...Traceback (most recent call last):
  File "/home/mtm/.local/bin/portablemc", line 8, in <module>
    sys.exit(main())
  File "/home/mtm/.local/lib/python3.10/site-packages/portablemc/cli.py", line 145, in main
    cmd(handler, ns)
  File "/home/mtm/.local/lib/python3.10/site-packages/portablemc/cli.py", line 314, in cmd
    handler(ns, new_context(ns))
  File "/home/mtm/.local/lib/python3.10/site-packages/portablemc/cli.py", line 724, in wrapper
    return func(orig_func, *w_args, **w_kwargs)
  File "/home/mtm/.local/lib/python3.10/site-packages/portablemc_forge/__init__.py", line 30, in cmd_start
    return old(ns, ctx)
  File "/home/mtm/.local/lib/python3.10/site-packages/portablemc/cli.py", line 380, in cmd_start
    version = new_version(ctx, ns.version)
  File "/home/mtm/.local/lib/python3.10/site-packages/portablemc/cli.py", line 724, in wrapper
    return func(orig_func, *w_args, **w_kwargs)
  File "/home/mtm/.local/lib/python3.10/site-packages/portablemc_forge/__init__.py", line 91, in new_version
    installer.install()
  File "/home/mtm/.local/lib/python3.10/site-packages/portablemc_forge/__init__.py", line 230, in install
    os.remove(self.installer_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mtm/.minecraft/versions/forge-1.19-41.0.100/installer.jar'
```
And it's at 100% as I begin the install.

**To Reproduce**
PortableMC version: 3.0.3
Python version: 3.10.4
Add-ons: Forge
On Xubuntu 20.4, I ran: `pip3 install portablemc-forge` `portablemc start forge:`

**Expected behavior**
Forge to start.

**Screenshots**

**Additional context**
I see the `installer.jar` show up and suddenly disappear at the same time as the error occurs.
I'm not sure if it gets removed just before or after the error.

And thanks for the launcher, runs Vanilla better than any launcher! (It really is fast, lightweight and portable!)

**Comment by mindstorm38** [comment]
Fixed both by @MTM828 and me 👍
